version: "3.9"
services:
  database:
    image: postgres:14
    container_name: database
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: Transport_Company
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - database 
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/Transport_Company"
    ports:
      - "5000:5000"
    command: npm run start

volumes:
  db_data:
